### ISSUE TITLE
unknow character wrote to the log file

### ISSUE THREAD

**Issue by crazybits** [op/go-logging#115]
i need to set the log level, so i create 3 backends, the console logging looks good, but there are some unknown character wrote the debug and infor log file, and also find the additional infor `33m` is added before the timestamp, the log content the code are attached, any hint?

**Log content:**
> [32m2017-06-16 18:26:13.643 main ▶ NOTI 003[0m notice
[33m2017-06-16 18:26:13.643 main ▶ WARN 004[0m warning
[31m2017-06-16 18:26:13.643 main ▶ ERRO 005[0m err
[35m2017-06-16 18:26:13.643 main ▶ CRIT 006[0m crit

**Source code:**
> 	debugFile, _ := os.OpenFile("debug.log", os.O_RDWR|os.O_APPEND|os.O_CREATE, 0644)
	infoFile, _ := os.OpenFile("info.log", os.O_RDWR|os.O_APPEND|os.O_CREATE, 0644)
	consoleBackend := logging.NewLogBackend(os.Stdout, "", 0)
	debugLogBackend := logging.NewLogBackend(debugFile, "", 0)
	infoLogBackend := logging.NewLogBackend(infoFile, "", 0)

	consoleBackendFormtter := logging.NewBackendFormatter(consoleBackend, format)
	debugBackendFormatter := logging.NewBackendFormatter(debugLogBackend, format)
	infoBackendFormatter := logging.NewBackendFormatter(infoLogBackend, format)

	consoleBackendLeveled := logging.AddModuleLevel(consoleBackendFormtter)
	consoleBackendLeveled.SetLevel(logging.WARNING, "")

	infoBackendLeveled := logging.AddModuleLevel(infoBackendFormatter)
	infoBackendLeveled.SetLevel(logging.INFO, "")

	logging.SetBackend(consoleBackendLeveled, debugBackendFormatter, infoBackendLeveled)

	log.Debugf("debug %s", Password("secret"))
	log.Info("info")
	log.Notice("notice")
	log.Warning("warning")
	log.Error("err")
	log.Critical("crit")

**Comment by JonasProgrammer** [comment]
The \[0m stuff is part of ANSI terminal formatting. On console this will be interpreted to change the output color, in files it'll just print as regular characters.
I guess you have %{color} in your format specification somewhere? If so, use another format specification for the file backend and ommit the %{color} part in the formatter.

**Comment by crazybits** [comment]
@JonasProgrammer you are awesome, issue solved after removing the %{color} part, thanks
