### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by zerjioang** [op/go-logging#139]
Is there a way that I can use your logger and disable logging featured on specific methods?
I have this needs, because I dont want the information to be logged while running benchmark, and my only option right now is to comment the lines in where the logger is used, which is kind of bullshit job,

Any advise on how to disable logging?

**Comment by Zamiell** [comment]
just write your own wrapper, e.g.
https://github.com/Zamiell/hanabi-live/blob/master/src/logger.go
