### ISSUE TITLE
[Question] How to log to a file?

### ISSUE THREAD

**Issue by stokito** [op/go-logging#149]
I'm new to go and I want to log to a file. Could you please add an example of file logging?
As far I understood it should look like:

	file, err := os.OpenFile("logs.txt", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	backend1 := logging.NewLogBackend(file, "", 0)

Did I wrote this correctly?

**Comment by hanqingwu** [comment]
yes, you're right
