### ISSUE TITLE
Global logger

### ISSUE THREAD

**Issue by johntdyer** [op/go-logging#15]
hello,

Sorry if this is a somewhat stupid question, but I am trying to define a global logger which I would use it multiple fils within my project.   The structure is pretty simple:

```
src/
    tlookup.go  # main()
    papi.go      # rest 
    utils.go      # utils
```

the problem i am having is that if I define it in the main then I cant seem to reference the logger in methods in my other files.  Any pointers you could git would be great.  Thanks ! 

Thanks

-John

**Comment by herkyl** [comment]
You figured it out but how does it work?
