### ISSUE TITLE
Formatting versions

### ISSUE THREAD

**Issue by jbenet** [op/go-logging#29]
@op not really sure what the right interface is -- you know best. But it strikes me that since the logging functions take formatting, maybe they should follow stdlib practice of having both `Name(string)` and `Namef(string, ...interface{})` variants.

Random reason to lean towards the extra `f`: lint errors like this:
![](https://www.evernote.com/shard/s198/sh/983c07b4-c43f-4b0d-8db7-854684d753cb/93480ae56a8bc5f4e3cf98f126c5cb6d/deep/0/handshake.go----Users-jbenet-go-src-github.com-jbenet-go-ipfs.png)

**Comment by optimality** [comment]
What about (for example) just introducing Errorf as an alias for Error?  That would enable us to use Errorf to avoid go vet noise without breaking backwards compatibility.

**Comment by nwolff** [comment]
@optimality it looks like an ok short-term solution if @op does not want to create a v2

The main remaining problem would be that some non-f methods such as Error expect a format, while others such as Panic don't, making things somewhat confusing. See: https://github.com/op/go-logging/blob/master/logger.go#L208-L211

**Comment by optimality** [comment]
@op Have you reached a decision on this?

**Comment by gdm85** [comment]
Sorry, but if ``go vet`` reports an error by default with this, I'd prefer to stick to ``go vet`` and fork/fix the bug.

**Comment by gdm85** [comment]
Right now I am using this syntax to workaround the problem:
```
go tool vet -printfuncs=Printf,Sprintf,Fprintf,Logf,Errorf,Fatalf,Warningf,Debugf src/
```

It would be best if I could get rid of this incomplete and error-prone workaround...

**Comment by op** [comment]
This is fixed now.
