### ISSUE TITLE
Color property has no effect on log output

### ISSUE THREAD

**Issue by guycalledseven** [op/go-logging#31]
NewLogBackend.Color property has no effect when custom format with colors are supplied to SetFormatter. So having one backend to write to a file and colors in console in other is a no go. :(
```
	log_format := "%{color}[%{level:.4s}] %{time:15:04:05.000000} %{id:03x} %{shortfile} [%{longpkg}] %{longfunc} -> %{color:reset}%{message}"
	logging.SetFormatter(logging.MustStringFormatter(log_format))
```
If I am reading this correctly Record.Formatted and stringFormatter Format have no information about color from backend. If they would, it would be trivial to add really cool functionality like per backend formats and log details.

**Comment by op** [comment]
I believe this is fixed already.
