### ISSUE TITLE
any function to do a log rotation?

### ISSUE THREAD

**Issue by jiang-wei** [op/go-logging#32]
Is there a function to set the log rotation?
otherwise I have to write some function to:
1. setup a new LogBackend with a new filename and replace the current Backend
2. rename the old log file to xxx.log.$DATETIME
3. rename the new log file to xxx.log

**Comment by cedricve** [comment]
This library is great: https://github.com/natefinch/lumberjack.

    fileBackend := logging.NewLogBackend(&lumberjack.Logger{
    Filename:   "./logs/log.log",
    MaxSize:    2, // megabytes
    Compress:   true, // disabled by default
	}, "", 0)
	logging.SetBackend(stdBackendLeveled, mqttBackend, fileBackend)
