### ISSUE TITLE
How could I print log both on screen and file by using go-logging

### ISSUE THREAD

**Issue by catric** [op/go-logging#43]
I followed the example, and I tried to use logging.MultiLogger, but it failed. could you please tell me how to resolve my problem? Thanks!!

my code as below
=================================================================================
	var format = logging.MustStringFormatter("[%{time:15:04:05.000}][%{shortfunc}][%{level:.4s}] %{message}")

	beScreen := logging.NewLogBackend(os.Stdout, "", 0)

	logfile := "log/test.log"
	file, _ := os.OpenFile(logfile, os.O_RDWR|os.O_CREATE, 0666)
	beFile := logging.NewLogBackend(file, "", 0)

	beScreenFormatter := logging.NewBackendFormatter(beScreen, format)
	beFileFormatter := logging.NewBackendFormatter(beFile, format)

	beScreenLeveled := logging.AddModuleLevel(beScreenFormatter)
	beScreenLeveled.SetLevel(logging.ERROR, "")

	beFileLeveled := logging.AddModuleLevel(beFileFormatter)
	beFileLeveled.SetLevel(logging.ERROR, "")

	// Set 2 backends to be used.
	logging.MultiLogger(beScreenLeveled, beFileLeveled)

**Comment by op** [comment]
Sorry for late reply, this slipped my radar. Try using `SetBackend` instead of the `MultiLogger`. If SetBackend is called with multiple loggers, they are wrapped as a MultiLogger automatically.
