### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by jbenet** [op/go-logging#44]
Suppose I have a logger, and i want to prefix its output. Pseudo example:

```Go
func factorial(log prefix.Logger, i int) {
  log = log.Prefix("%d", i)
  log.Debug("enter")
  defer log.Debug("exit")

  switch {
  case i < 0:
    log.Error("is negative!")
    return 0
  case i == 0, i == 1:
    return 1
  default:
    return i * factorial(log, i - 1)
  }
}

func main() {
  n, _ := strconv.Atoi(os.Args[1])
  log := prefix.Logger("factorial")
  log = log.Prefix("factorial:")
  fmt.Printf("%d", factorial(log, n))
}
```
```
> go run main.go 4
factorial: 4 enter
factorial: 4 3 enter
factorial: 4 3 2 enter
factorial: 4 3 2 1 enter
factorial: 4 3 2 1 exit
factorial: 4 3 2 exit
factorial: 4 3 exit
factorial: 4 exit
24

> go run main.go -10
factorial: -10 enter
factorial: -10 is negative!
factorial: -10 exit
0
```

I implemented this: https://gist.github.com/jbenet/70ff524c460986eab6c3 which does what I want. (extracted from go-ipfs). BUT, the issue is the filename breaks, because op/go-logging _assumes_ the runtime calldepth is at a particular place in the stack, and that its logger is not being wrapped.

So, if not wrapping, then it has to be done _within_ a `logging.Logger`.
- could wrap a `Backend`? can't get the logger's current backend, and the `Record`'s fields are private.
- could wrap the `Formatter`? the logger is not associated with a formatter. see backend.

Suggestions?

**Comment by giftig** [comment]
#42 though it has a couple of issues to iron out.

**Comment by jbenet** [comment]
@giftig ah perfect
