### ISSUE TITLE
experimental websocket backend

### ISSUE THREAD

**Issue by cryptix** [op/go-logging#46]
Hi,

I'm experimented a little with exposing logs over websockets. The [backend](https://godoc.org/github.com/cryptix/go/logging/wslog) exposes a net/http Handler which upgrades requests to websocket connections (it uses the gorilla ws pkg) and registers them. Records given to the backend are than broadcasted to all registered connections.

I just thought I share this for others to see how easy it is to implement your own backends. If there is interest i'd be happy to refine it and open a PR.

Possible areas of improvement:

- Implement `Leveled` per ws connection and let clients control this
- Format to JSON
- ???

**Comment by op** [comment]
That is very cool! Thanks for sharing. I added a link to wslog in the README.

**Comment by jackiesun8** [comment]
wslog not found now~

**Comment by cryptix** [comment]
sorry. I moved the code [here](https://godoc.org/github.com/cryptix/exp/wslog).

**Comment by jackiesun8** [comment]
@cryptix thanks. excellent job.
