### ISSUE TITLE
too much cpu time being spent even in loglevels below current level

### ISSUE THREAD

**Issue by Dieterbe** [op/go-logging#50]
hi, i have an app that does quite a bit of log traffic (potentially thousands of messages per second depending on which log level).  I was troubleshooting an issue today (https://github.com/graphite-ng/carbon-relay-ng/issues/57) and noticed that we spend quite some cpu time in logging functions that are below the current log level.  for example in Debug() when level is set to warning.
![logging-profile](https://cloud.githubusercontent.com/assets/20774/6585705/27255a7a-c74a-11e4-9029-9b2a21a8d9f7.png)
I notice that when we call `(l *Logger) log` it spends time creating a new record, allocating memory and increasing atomic sequence numbers.
and then in the `LogBackend Log()` it does a bunch more allocations and function calls, and then calls log.Logger. I didn't study all the code in detail, but why not just check the current loglevel first and bypass all the logic when we don't need it?

**Comment by op** [comment]
Good question. Not sure what the reasoning behind it was either but it sounds like a sane change. I'll have a look at it!

**Comment by op** [comment]
There are no allocations at all now if you pass in a fixed string. The overhead is just a couple of nanoseconds (~30ns).

If you do pass in string for format, eg. `("foo %s", bar)`, there will be some allocations and the overhead is on my machine ~400ns (compared to 1400ns as it was previously). The compiler should be able to optimise for this case in the future I hope. This is just how Go works I suppose.

Good catch. Hope this helps!

**Comment by Dieterbe** [comment]
sweet. thanks for the quick fix!
