### ISSUE TITLE
Add per-level formatter

### ISSUE THREAD

**Issue by henryx** [op/go-logging#58]
Currently Formatter is usable only in backend logger. In some cases (e.g. for debug messages) is preferable to apply a different Formatter without touch the backend. So, in this case, it would be useful to apply the Formatter in level functions (e.g. log.Debug("message", formatter) )

**Comment by giftig** [comment]
Personally I would want all my log statements to be a consistent formatter, so the way it currently works makes sense to me. I can't think of a use case where per-level makes much sense to be honest. Why do you need debug-level messages to be formatted differently? You can always just add whatever debug info you need to the message.

**Comment by op** [comment]
That's not something I will add. If you do write the code, please send a PR and I might reconsider.

**Comment by henryx** [comment]
@giftig for example, I want to use the formatter "%{time:2006-01-02 15:04:05.000} %{level} - Application - %{message}" for all messages. In debug messages, I want to use the formatter "%{time:2006-01-02 15:04:05.000} %{level} %{longfunc}:%{id:03x} - Application - %{message}" because is very useful to know how the message is generated without replicate the code in every debug point. Alternatively, you need to codify all messages manually, and is very boring (and error prone)

**Comment by giftig** [comment]
Hm, I tend to find clear log messages gives you sufficient context, but to each their own I suppose. Of course, you can simply put your formatter in a configuration file along with logging level, so you could swap between the two formatters when swapping between, say, warning / debug level just by making a simple config change. I would have thought that level of functionality would be best left to the application.

**Comment by franciscocpg** [comment]
@henryx, this [pull request #60] (https://github.com/op/go-logging/pull/60) it's what you want?

**Comment by henryx** [comment]
@franciscocpg yes, is a good way for doing it
