### ISSUE TITLE
Error & Critical level logging issue

### ISSUE THREAD

**Issue by Jitendrakry** [op/go-logging#61]
Messages used in error and critical level logging are displayed separately before log message as logged in formatted manner

Sample output:

16:50:01.581 main . DEBU 001 debug ******
16:50:01.583 main . INFO 002 info
16:50:01.584 main . NOTI 003 notice
16:50:01.584 main . WARN 004 test
this is error level logging message
16:50:01.585 main . ERRO 005 this is error level logging message
this is critical level message
16:50:01.587 main . CRIT 006 this is critical level message

code example:

package main

import (
    "os"

    "github.com/op/go-logging"
)

var log = logging.MustGetLogger("example")

// Example format string. Everything except the message has a custom color
// which is dependent on the log level. Many fields have a custom output
// formatting too, eg. the time returns the hour down to the milli second.
var format = logging.MustStringFormatter(
    "%{color}%{time:15:04:05.000} %{shortfunc} . %{level:.4s} %{id:03x}%{color:reset} %{message}",
)

// Password is just an example type implementing the Redactor interface. Any
// time this is logged, the Redacted() function will be called.
type Password string

func (p Password) Redacted() interface{} {
    return logging.Redact(string(p))
}
func main() {
//test := "there are log of error i"

    // For demo purposes, create two backend for os.Stderr.
    backend1 := logging.NewLogBackend(os.Stderr, "", 0)
    backend2 := logging.NewLogBackend(os.Stderr, "", 0)

    // For messages written to backend2 we want to add some additional
    // information to the output, including the used log level and the name of
    // the function.
    backend2Formatter := logging.NewBackendFormatter(backend2, format)

    // Only errors and more severe messages should be sent to backend1
    backend1Leveled := logging.AddModuleLevel(backend1)
    backend1Leveled.SetLevel(logging.ERROR, "")

    // Set the backends to be used.
    logging.SetBackend(backend1Leveled, backend2Formatter)

    log.Debug("debug %s", Password("secret"))
    log.Info("info")
    log.Notice("notice")
    log.Warning("test")
    log.Error("this is error level logging message")
  //  log.Error("err")
    log.Critical("this is critical level message")
}

**Comment by allengeorge** [comment]
Interesting - I'm noticing this for "INFO" as well...

**Comment by EmileVauge** [comment]
Same for me...
Anybody to resolve that critical bug?

**Comment by EmileVauge** [comment]
OK I found it...
This is because you don't have to copy/paste the example...

```go
// Set the backends to be used.
    logging.SetBackend(backend1Leveled, backend2Formatter)
```

should be

```go
// Set the backends to be used.
    logging.SetBackend(backend2Formatter)
```

Funny ;)

**Comment by op** [comment]
Great. Thanks @emilevauge
