### ISSUE TITLE
NewLogBackend signature is different on *nix and Windows

### ISSUE THREAD

**Issue by vadimsht** [op/go-logging#69]
It causes errors when compiling on Win (but not on Linux\Mac).

Win: NewLogBackend(out *os.File, prefix string, flag int)
*nix: NewLogBackend(out io.Writer, prefix string, flag int)

https://github.com/op/go-logging/blob/master/log_windows.go#L54
https://github.com/op/go-logging/blob/master/log_nix.go#L40

In particular here's how we use go-logging: https://github.com/luci/luci-go/blob/master/common/logging/gologger/config.go#L30

It used to work fine, but after https://github.com/op/go-logging/commit/03393de130e556c06d1e90f3693cdbf279230595 it compiles on Linux\Mac, but not on Windows (causing some confusion).

----

IMHO, public API should look identical on all platforms. Requiring os.File everywhere may be a breaking change. What do you think about using io.Writer in NewLogBackend on Win too, but try to cast it to os.File (and enabling colors only if cast succeeds)?

**Comment by op** [comment]
Aikes. That's definitley something I overlooked and probably @zanderz too. Wouldn't make sense to have different signatures on different platforms.

I think your proposed solution makes sense. If you're interested in sending in a PR I would be more than happy to merge it.

Thanks for spotting this!

**Comment by zanderz** [comment]
Here is our use, which builds cross platform.
https://github.com/keybase/client/blob/master/go/logger/standard.go#L103

I agree that the interface should be the same on all platforms. Let me know if you would like me to do the change. Sorry about that!

**Comment by op** [comment]
@vadimsht @zanderz Would help me a lot if you could try this. I don't have access to a Windows machine.

**Comment by vadimsht** [comment]
Seems to be working. At least compiles, and produces valid looking log lines on Windows.

Thanks for the quick fix!
