### ISSUE TITLE
Stack Skip Count parameter

### ISSUE THREAD

**Issue by yoiang** [op/go-logging#81]
Hey @op !
As I mentioned in the previous issue on one project we have our own logging wrapper, as a result calling *go-logging* with formatting that dumps any sort of function call or file information will only product our logging wrapper. It'd be super nice to have a way to tell *go-logging* to skip X number of stack objects when it pulls the information.

**Comment by yoiang** [comment]
Nevermind, while exploring the library for another reason I just noticed `ExtraCalldepth` inside of `Logger`. Apologies for the bother :)

**Comment by giftig** [comment]
Hehe we ran into this problem as well so we patched it ;)

**Comment by yoiang** [comment]
@giftig awesome, thanks for adding it :)
