### ISSUE TITLE
Control/Observe exit code based on logging level?

### ISSUE THREAD

**Issue by bcbrock** [op/go-logging#86]
Hi Örjan,

I observe that if my application (which uses op/go-logging) ever issues a log message at level WARNING or higher, then when the application exits it exits with a non-zero exit code. So far I have not been able to figure out how this happens. Is this behavior controllable? Can it be observed? By that I mean if my main() is about to return (exit) how can I check if any part of the application has logged at WARNING or above and the program will return a on-0 code?

Thanks - Bishop Brock

**Comment by op** [comment]
Panic and Fatal functions do this. Does this explain your observation? Maybe you can provide us with a minimised example program.

**Comment by bcbrock** [comment]
Thank you for your reply, it was very helpful to know that go-logging was not causing this. It turns out that I was exec-ing the application (which logs to stderr) from a Tcl script, and I just learned that Tcl has the strange default behavior that if an exec-ed application writes anything to stderr it is considered a failure. Thanks again.
