### ISSUE TITLE
revert Error() api change

### ISSUE THREAD

**Issue by coryb** [op/go-logging#88]
In commit 0758a840 Error changed from 
`Error(format string, args ...interface{})`
to
`Error(args ...interface{})`

So now all of `Error` calls in my projects print the literal formats.  I am seeing stuff like:
```
err := fmt.Errorf("Error Message")
log.Error("Thing failed: %s", err)
```
now prints the format literally like:
```
Thing failed: %sError Message
```

I would say that the `Error` api should be no different than the other log level statements `Critical`, `Warning`, `Notice`, `Info`, `Debug`.  

So I kindly ask you to revert the `Error` api change made in 0758a840.

Thanks!
-Cory

**Comment by op** [comment]
I was maybe a bit trigger happy and looked at the methods above and noticed that the change looked fine. But looking at the methods below, you're right. This is just so inconsistent.

**Comment by coryb** [comment]
Nice, thanks!
-Cory

**Comment by op** [comment]
@coryb Sorry but I changed it again if you've seen my recent changes in master. Please use the `Infof` function if you want explicit formatting. Thanks for reporting!

**Comment by coryb** [comment]
Sigh, okay.  I see you just created a v1 tag, so I am going to switch to using 
`import "gopkg.in/op/go-logging.v1"`

Hopefully you can keep the version tags moving to help us be isolated from api changes of the sort.

Thanks
-Cory
